// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";
import type { ProcessTerminalSize } from "./ProcessTerminalSize";
import type { ThreadTerminalSource } from "./ThreadTerminalSource";
import type { ThreadTerminalStatus } from "./ThreadTerminalStatus";

export type ThreadTerminalInfo = { threadId: string, label: string, processId: string, command: string, cwd: AbsolutePathBuf, source: ThreadTerminalSource, tty: boolean, size: ProcessTerminalSize | null, status: ThreadTerminalStatus, };
