// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Catalog-owned policy for presenting a model's reasoning output.
 */
export type ModelReasoningDisplay = "summary" | "kimiRaw";
